# Generated by Django 5.2.5 on 2025-08-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
