# Generated by Django 5.2.5 on 2025-08-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_notification_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
